/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    SkeletonCard: typeof import('./src/components/SkeletonCard.vue')['default']
    ToastNotification: typeof import('./src/components/ToastNotification.vue')['default']
  }
}
