Config.Vehicles = { -- soit tu renseignes l'img en faisant img = chemin/vers/limage soit tu ne met rien et l'image choisi sera le nom du model.png a l'emplacement de img/vehicles/*.png
import = {
    {name = "A45", price = 2000, model = "a45amg", img = "https://i.ibb.co/6J12dMXK/a45amg.png", specs = {speed = 92, adhesion = 88, acceleration = 90, braking = 86, maniability = 87}},
    {name = "GTX-R", price = 2000, model = "rmodgtr", img = "https://i.ibb.co/RGtzRT9F/rmodgtr.png", specs = {speed = 94, adhesion = 87, acceleration = 93, braking = 85, maniability = 88}},
    {name = "C32", price = 2000, model = "benzc32", img = "https://i.ibb.co/tTm5ssw2/benzc32.png", specs = {speed = 89, adhesion = 85, acceleration = 88, braking = 84, maniability = 86}},
    {name = "Zouda", price = 2000, model = "rmodpagani", img = "https://i.ibb.co/3Y0wJhn2/rmodpagani.png", specs = {speed = 96, adhesion = 89, acceleration = 95, braking = 87, maniability = 91}},
    {name = "M4 GTS", price = 2000, model = "rmodm4gts", img = "https://i.ibb.co/hFcnN8L9/rmodm4gts.png", specs = {speed = 93, adhesion = 86, acceleration = 92, braking = 85, maniability = 89}},
    {name = "Cayan", price = 2000, model = "cayen19", img = "https://i.ibb.co/5Ws89fCz/cayen19.png", specs = {speed = 88, adhesion = 90, acceleration = 87, braking = 84, maniability = 85}},
    {name = "8R", price = 2000, model = "golf8gti", img = "https://i.ibb.co/W4839kLp/golf8gti.webp", specs = {speed = 90, adhesion = 87, acceleration = 89, braking = 85, maniability = 88}},
    {name = "E39", price = 2000, model = "mteche39", img = "https://i.ibb.co/QFLYqg2z/mteche39.png", specs = {speed = 89, adhesion = 85, acceleration = 88, braking = 83, maniability = 86}},
    {name = "Prestige", price = 2000, model = "passat", img = "https://i.ibb.co/XZrBdmtC/passat.webp", specs = {speed = 87, adhesion = 84, acceleration = 86, braking = 83, maniability = 84}},
    {name = "C63", price = 2000, model = "c63hr", img = "https://i.ibb.co/sdscvsS2/c63hr.webp", specs = {speed = 94, adhesion = 88, acceleration = 93, braking = 86, maniability = 88}},
    {name = "Amarox", price = 2000, model = "amarok", img = "https://i.ibb.co/93rhPfDX/amarok.webp", specs = {speed = 85, adhesion = 90, acceleration = 84, braking = 82, maniability = 83}},
    {name = "M4", price = 2000, model = "m4c", img = "https://i.ibb.co/Lh01BY1Q/m4c.png", specs = {speed = 92, adhesion = 87, acceleration = 91, braking = 86, maniability = 89}},
    {name = "Scharmann", price = 2500, model = "scharmann", img = "https://i.ibb.co/9HjhWqsw/scharmann.png", specs = {speed = 91, adhesion = 88, acceleration = 90, braking = 86, maniability = 87}},
    {name = "Argento", price = 2500, model = "argento", img = "https://i.ibb.co/4wNh3yVr/argento.png", specs = {speed = 90, adhesion = 87, acceleration = 88, braking = 85, maniability = 86}},
    {name = "Scheisser", price = 2500, model = "scheisser", img = "https://i.ibb.co/mrjxV3GF/scheisser.png", specs = {speed = 92, adhesion = 89, acceleration = 91, braking = 87, maniability = 88}},
    {name = "Evo 9", price = 2500, model = "evo9", img = "https://i.ibb.co/RpSWmmZV/evo9.png", specs = {speed = 93, adhesion = 90, acceleration = 94, braking = 86, maniability = 89}},
    {name = "FC450", price = 2500, model = "fc450", img = "https://i.ibb.co/4RNXkF99/fc450.webp", specs = {speed = 90, adhesion = 84, acceleration = 93, braking = 83, maniability = 95}},
    {name = "SF-X 450", price = 3000, model = "sxf450sm", img = "https://i.ibb.co/yBd6cfZk/sxf450sm.png", specs = {speed = 91, adhesion = 85, acceleration = 94, braking = 84, maniability = 96}},
    {name = "Nuit Noir", price = 3000, model = "rmodbugatti", img = "https://i.ibb.co/5XdjHcgw/rmodbugatti.png", specs = {speed = 98, adhesion = 92, acceleration = 97, braking = 90, maniability = 93}},
    {name = "Q8", price = 3000, model = "q8prior", img = "https://i.ibb.co/SwsRyqqy/q8prior.png", specs = {speed = 89, adhesion = 92, acceleration = 87, braking = 85, maniability = 84}},
    {name = "E36", price = 3000, model = "rmodm3e36", img = "https://i.ibb.co/MDQqn3n4/rmodm3e36.png", specs = {speed = 92, adhesion = 86, acceleration = 91, braking = 85, maniability = 87}},
    {name = "R666S", price = 3000, model = "rs666", img = "https://i.ibb.co/nqdKPSGG/rs666.png", specs = {speed = 93, adhesion = 87, acceleration = 92, braking = 86, maniability = 88}},
    {name = "Compact Sport", price = 3000, model = "rmodmk7", img = "https://i.ibb.co/Q3CBg6N0/rmodmk7.png", specs = {speed = 91, adhesion = 86, acceleration = 89, braking = 85, maniability = 87}},
    {name = "GT 63S", price = 3000, model = "rmodgt63", img = "https://i.ibb.co/8n0jB9ks/rmodgt63.png", specs = {speed = 94, adhesion = 88, acceleration = 93, braking = 87, maniability = 89}},
    {name = "XB7", price = 3000, model = "20xb7", img = "https://i.ibb.co/cVtbxFQ/20xb7.png", specs = {speed = 88, adhesion = 91, acceleration = 86, braking = 84, maniability = 83}},
    {name = "RS6 ABT", price = 3000, model = "rs6abt20", img = "https://i.ibb.co/gZ01dv2x/rs6abt20.png", specs = {speed = 93, adhesion = 90, acceleration = 92, braking = 86, maniability = 87}},
    {name = "F40", price = 3000, model = "rmodf40", img = "https://i.ibb.co/Y4mGvrXG/rmodf40.png", specs = {speed = 95, adhesion = 88, acceleration = 94, braking = 85, maniability = 89}},
    {name = "Uros SUV", price = 3000, model = "1016urus", img = "https://i.ibb.co/rTRMZcf/1016urus.png", specs = {speed = 90, adhesion = 92, acceleration = 89, braking = 87, maniability = 84}},
    {name = "Vela", price = 3000, model = "18Velar", img = "https://i.ibb.co/JFHV4T62/18Velar.png", specs = {speed = 88, adhesion = 90, acceleration = 86, braking = 84, maniability = 83}},
    {name = "RS3", price = 3000, model = "rs318", img = "https://i.ibb.co/Xr6VTFHS/rs318.png", specs = {speed = 91, adhesion = 87, acceleration = 90, braking = 85, maniability = 87}},
    {name = "E63", price = 3000, model = "rmode63s", img = "https://i.ibb.co/39TTSc0C/rmode63s.png", specs = {speed = 94, adhesion = 89, acceleration = 92, braking = 87, maniability = 88}},
    {name = "Grande 4x4", price = 3000, model = "demonhawkk", img = "https://i.ibb.co/SXhR2Bhd/demonhawkk.webp", specs = {speed = 87, adhesion = 92, acceleration = 85, braking = 84, maniability = 82}},
    {name = "B63S", price = 3000, model = "b63s", img = "https://i.ibb.co/s9SFXG1Z/b63s.webp", specs = {speed = 93, adhesion = 88, acceleration = 92, braking = 87, maniability = 88}},
    {name = "Civica Type-R", price = 3000, model = "animfk8hr", img = "https://i.ibb.co/tpYpKdvm/animfk8hr.jpg", specs = {speed = 90, adhesion = 86, acceleration = 89, braking = 85, maniability = 87}},
    {name = "A4 Quattro", price = 3000, model = "aaq4", img = "https://i.ibb.co/ymnDtD2L/aaq4.webp", specs = {speed = 89, adhesion = 88, acceleration = 88, braking = 85, maniability = 86}},
    {name = "R8 V10", price = 3000, model = "r820", img = "https://i.ibb-co/R4VnmVK2/r820.png", specs = {speed = 96, adhesion = 90, acceleration = 95, braking = 88, maniability = 90}},
    {name = "M5", price = 3000, model = "22M5", img = "https://i.ibb.co/XZgNzhXW/22M5.png", specs = {speed = 94, adhesion = 89, acceleration = 93, braking = 87, maniability = 88}},
    {name = "CLA45", price = 3000, model = "2020CLA45s", img = "https://i.ibb.co/wNV6jVhg/2020-CLA45s.png", specs = {speed = 92, adhesion = 87, acceleration = 91, braking = 85, maniability = 88}},
    {name = "GLE", price = 3000, model = "gta5rp_veh_gle1", img = "https://i.ibb.co/7dktWmfB/gta5rp-veh-gle1.png", specs = {speed = 88, adhesion = 91, acceleration = 87, braking = 84, maniability = 83}},
    {name = "J65", price = 3000, model = "rmodg65", img = "https://i.ibb.co/BH0jTkf5/rmodg65.png", specs = {speed = 87, adhesion = 90, acceleration = 86, braking = 84, maniability = 82}},
    {name = "Atlantic Sport", price = 3000, model = "rmodatlantic", img = "https://i.ibb.co/RTk2RNgV/rmodatlantic.png", specs = {speed = 97, adhesion = 92, acceleration = 96, braking = 89, maniability = 92}},
    {name = "TMAX 530", price = 3000, model = "tmaxdx", img = "https://i.ibb.co/ZztwqndN/tmaxdx.png", specs = {speed = 90, adhesion = 84, acceleration = 92, braking = 82, maniability = 97}},
    {name = "Prime Electric", price = 3000, model = "teslapd", img = "https://i.ibb.co/V0f56T6v/teslapd.png", specs = {speed = 94, adhesion = 89, acceleration = 98, braking = 88, maniability = 89}},
    {name = "F812", price = 3000, model = "f812", img = "https://i.ibb.co/pvT2DHBJ/f812.png", specs = {speed = 97, adhesion = 90, acceleration = 96, braking = 88, maniability = 91}},
    {name = "SpeedSport 300", price = 3000, model = "chironsupersport22", img = "https://i.ibb.co/dsV3ytnX/chironsupersport22.png", specs = {speed = 98, adhesion = 92, acceleration = 97, braking = 90, maniability = 93}},
    {name = "Dawn Onyx", price = 3000, model = "dawnonyx", img = "https://i.ibb.co/0pYVp3Ty/dawnonyx.png", specs = {speed = 90, adhesion = 88, acceleration = 89, braking = 85, maniability = 86}},
    {name = "675LT", price = 3000, model = "675lt", img = "https://i.ibb.co/bjVY3n7Q/675lt.png", specs = {speed = 96, adhesion = 89, acceleration = 95, braking = 88, maniability = 91}},
    {name = "SIAN", price = 3000, model = "sian", img = "https://i.ibb.co/qMhm2rkQ/sian.png", specs = {speed = 97, adhesion = 91, acceleration = 96, braking = 89, maniability = 92}},
    {name = "GTR 34", price = 3000, model = "rmodskyline34", img = "https://i.ibb.co/j9jgnLNH/rmodskyline34.png", specs = {speed = 94, adhesion = 88, acceleration = 93, braking = 86, maniability = 89}},
    {name = "Supra Pandem", price = 3000, model = "suprapandem", img = "https://i.ibb.co/67YF3Y67/suprapandem.png", specs = {speed = 92, adhesion = 87, acceleration = 91, braking = 85, maniability = 88}},
    {name = "RS7", price = 3000, model = "rs7", img = "https://i.ibb.co/wFb7kqKP/rs7.png", specs = {speed = 94, adhesion = 89, acceleration = 93, braking = 87, maniability = 88}},
    {name = "M5 E60", price = 3000, model = "m5e60", img = "https://i.ibb.co/JRcT5w7d/m5e60.webp", specs = {speed = 93, adhesion = 88, acceleration = 92, braking = 86, maniability = 87}},
    {name = "Huracan Beast", price = 3000, model = "huracanpriorbeast", img = "https://i.ibb.co/5PPpqLm/huracanpriorbeast.png", specs = {speed = 97, adhesion = 90, acceleration = 96, braking = 88, maniability = 92}},
    {name = "RS6 Avant", price = 3000, model = "rs615", img = "https://i.ibb.co/prKCwqBP/rs615.png", specs = {speed = 92, adhesion = 90, acceleration = 91, braking = 87, maniability = 86}},
    {name = "AMG One", price = 3000, model = "amgone", img = "https://i.ibb.co/nM2RvYVQ/amgone.png", specs = {speed = 99, adhesion = 93, acceleration = 98, braking = 91, maniability = 93}},
},
    sport = {
        {name = 'Adder', price = 1500, model = 'adder', img = 'https://docs.fivem.net/vehicles/adder.webp', specs = {speed = 100, adhesion = 95, acceleration = 98, braking = 90, maniability = 85}},
        {name = 'Entity XF', price = 1500, model = 'entityxf', img = 'https://docs.fivem.net/vehicles/entityxf.webp', specs = {speed = 99, adhesion = 92, acceleration = 97, braking = 88, maniability = 87}},
        {name = 'Zentorno', price = 1500, model = 'zentorno', img = 'https://docs.fivem.net/vehicles/zentorno.webp', specs = {speed = 100, adhesion = 93, acceleration = 99, braking = 89, maniability = 88}},
        {name = 'T20', price = 1500, model = 't20', img = 'https://docs.fivem.net/vehicles/t20.webp', specs = {speed = 98, adhesion = 91, acceleration = 96, braking = 87, maniability = 89}},
        {name = 'Osiris', price = 1500, model = 'osiris', img = 'https://docs.fivem.net/vehicles/osiris.webp', specs = {speed = 99, adhesion = 94, acceleration = 97, braking = 90, maniability = 86}},
    },
    suv = {
        {name = 'Baller', price = 1500, model = 'baller', img = 'https://docs.fivem.net/vehicles/baller.webp', specs = {speed = 75, adhesion = 70, acceleration = 72, braking = 68, maniability = 65}},
        {name = 'Cavalcade', price = 1500, model = 'cavalcade', img = 'https://docs.fivem.net/vehicles/cavalcade.webp', specs = {speed = 72, adhesion = 68, acceleration = 70, braking = 65, maniability = 62}},
        {name = 'Dubsta', price = 1500, model = 'dubsta', img = 'https://docs.fivem.net/vehicles/dubsta.webp', specs = {speed = 78, adhesion = 72, acceleration = 74, braking = 70, maniability = 67}},
        {name = 'FQ 2', price = 1500, model = 'fq2', img = 'https://docs.fivem.net/vehicles/fq2.webp', specs = {speed = 76, adhesion = 71, acceleration = 73, braking = 69, maniability = 66}},
        {name = 'Granger', price = 1500, model = 'granger', img = 'https://docs.fivem.net/vehicles/granger.webp', specs = {speed = 77, adhesion = 73, acceleration = 75, braking = 71, maniability = 68}},
    },
    drift = {
        {name = 'Futo', price = 1500, model = 'futo', img = 'https://docs.fivem.net/vehicles/futo.webp', specs = {speed = 82, adhesion = 75, acceleration = 78, braking = 70, maniability = 95}},
        {name = 'Kuruma', price = 1500, model = 'kuruma', img = 'https://docs.fivem.net/vehicles/kuruma.webp', specs = {speed = 85, adhesion = 80, acceleration = 82, braking = 75, maniability = 88}},
        {name = 'Banshee', price = 1500, model = 'banshee', img = 'https://docs.fivem.net/vehicles/banshee.webp', specs = {speed = 88, adhesion = 78, acceleration = 85, braking = 72, maniability = 92}},
        {name = 'Carbonizzare', price = 1500, model = 'carbonizzare', img = 'https://docs.fivem.net/vehicles/carbonizzare.webp', specs = {speed = 92, adhesion = 82, acceleration = 90, braking = 80, maniability = 90}},
    },
    moto = {
        {name = 'Bati 801', price = 1500, model = 'bati', img = 'https://docs.fivem.net/vehicles/bati.webp', specs = {speed = 95, adhesion = 85, acceleration = 92, braking = 80, maniability = 98}},
        {name = 'Double T', price = 1500, model = 'double', img = 'https://docs.fivem.net/vehicles/double.webp', specs = {speed = 88, adhesion = 82, acceleration = 85, braking = 75, maniability = 95}},
        {name = 'Hakuchou', price = 1500, model = 'hakuchou', img = 'https://docs.fivem.net/vehicles/hakuchou.webp', specs = {speed = 98, adhesion = 90, acceleration = 95, braking = 82, maniability = 96}},
    },
    boat = {
        {name = 'Dinghy', price = 1500, model = 'dinghy', img = 'https://docs.fivem.net/vehicles/dinghy.webp', specs = {speed = 65, adhesion = 60, acceleration = 62, braking = 55, maniability = 70}},
        {name = 'Jetmax', price = 1500, model = 'jetmax', img = 'https://docs.fivem.net/vehicles/jetmax.webp', specs = {speed = 80, adhesion = 75, acceleration = 78, braking = 70, maniability = 75}},
        {name = 'Seashark', price = 1500, model = 'seashark', img = 'https://docs.fivem.net/vehicles/seashark.webp', specs = {speed = 72, adhesion = 68, acceleration = 70, braking = 62, maniability = 80}},
    },
    airplane = {
        {name = 'Velum', price = 3000, model = 'velum', img = 'https://docs.fivem.net/vehicles/velum.webp', specs = {speed = 85, adhesion = 80, acceleration = 82, braking = 75, maniability = 75}},
        {name = 'Luxor', price = 3000, model = 'luxor', img = 'https://docs.fivem.net/vehicles/luxor.webp', specs = {speed = 95, adhesion = 90, acceleration = 92, braking = 88, maniability = 80}},
    },
}

Config.Type = {
    import = 'car',     
    sport = 'car',      
    suv = 'car',        
    drift = 'car',      
    blinde = 'car',     
    moto = 'car',       
    boat = 'boat',      
    airplane = 'aircraft', 
}

Config.TestCoords = vector4(-1700.38, -2939.25, 13.3, 240.0)
Config.TestTime = 60 -- secondes